/**
 * Copies third-party browser bundles from node_modules into www/vendor and builds www/css/tailwind.css,
 * so the app (Capacitor + PWA) runs without CDNs. Run: npm run vendor
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const OUT = path.join(ROOT, 'www', 'vendor');

const FILES = [
  ['chart.js/dist/chart.umd.min.js', 'chart.umd.min.js'],
  ['@supabase/supabase-js/dist/umd/supabase.js', 'supabase.js'],
  ['@supabase/supabase-js/dist/umd/591.supabase.js', '591.supabase.js']
];

// Quicksand (SIL OFL 1.1), self-hosted so text renders the same offline. Only the woff2 files are copied;
// www/css/fonts.css declares them under the family name the app already uses ('Quicksand').
const FONT_DIR = path.join(ROOT, 'www', 'fonts');
const FONT_FILES = ['vietnamese', 'latin-ext', 'latin'].map((s) => 'quicksand-' + s + '-wght-normal.woff2');

fs.mkdirSync(OUT, { recursive: true });
for (const [from, to] of FILES) {
  fs.copyFileSync(path.join(NM, from), path.join(OUT, to));
  console.log('vendor', to);
}

fs.mkdirSync(FONT_DIR, { recursive: true });
for (const f of FONT_FILES) {
  fs.copyFileSync(path.join(NM, '@fontsource-variable', 'quicksand', 'files', f), path.join(FONT_DIR, f));
  console.log('font', f);
}
const fontCss = fs.readFileSync(path.join(NM, '@fontsource-variable', 'quicksand', 'index.css'), 'utf8')
  .replace(/'Quicksand Variable'/g, "'Quicksand'")
  .replace(/url\(\.\/files\//g, 'url(../fonts/');
fs.writeFileSync(path.join(ROOT, 'www', 'css', 'fonts.css'), '/* Generated by tools/vendor_assets.js from @fontsource-variable/quicksand (SIL OFL 1.1). */\n' + fontCss);

execFileSync(process.execPath, [
  path.join(NM, 'tailwindcss', 'lib', 'cli.js'),
  '-c', path.join(ROOT, 'tailwind.config.js'),
  '-i', path.join(ROOT, 'src', 'tailwind.css'),
  '-o', path.join(ROOT, 'www', 'css', 'tailwind.css'),
  '--minify'
], { stdio: 'inherit', cwd: ROOT });
